### ISSUE TITLE
[suggestion] add server-side configurable

### ISSUE THREAD

**Issue by superon** [adamviola/EntityOutliner#1]
i'd like to use this to allow players to only view other players :)

**Comment by adamviola** [comment]
We could add this feature, but it would require a server with Fabric installed to use. A much more general approach would be to not use the mod at all, and instead give all players the Glowing status effect via command blocks. What do you think?

**Comment by superon** [comment]
i was thinking about it being server-side, would this work as a datapack perhaps?   also how far is this effect visible from, does it depend on render distance.. i assume it does so would there be a way to add something so they're visible server-wide (re: similar to this...  https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/requests-ideas-for-mods/3043186-flares-and-glares)?

**Comment by superon** [comment]
the intention here is to be able to let other players know where you are wherever you are, at a glance

**Comment by superon** [comment]
i realise this idea is not your mod, so with that said the direction it takes should totally be up to you :)

**Comment by adamviola** [comment]
Yes, the effect only works as long as the entity is within render distance. A datapack would be a great way to implement this feature for a server.

I certainly like the idea of being able to see players no matter where they are, but that is an entirely different mod from Entity Outliner. I personally enjoy working on clientside-style mods, but I do appreciate the suggestion!
