### ISSUE TITLE
White outline on entities that spawned while the outline was toggled ON

### ISSUE THREAD

**Issue by CofiPRT** [adamviola/EntityOutliner#11]
I've had this happening to me, I've seen it in the comments on CurseForge, and I think I broke it down to these simple steps.

1. Enable the outline for an entity.
2. Toggle **ON** the outlines.
3. Spawn an entity of that type. The `summon` command works too.
4. Toggle **OFF** the outlines.

The spawned entity should be outlined in white as long as the outlines are toggled **OFF**.

**[Extra Info]** bug seems to go away when:
- teleporting far away from the affected entity/entities, then teleporting back
- teleporting through a portal (nether), and back
- rejoining the world

Tested on the latest version available at the time of writing. If these steps still find you unable to replicate the bug, it may be a combination of two mods. I have a substantial amount of mods, hence I'll do this further research only if it's required.

**Comment by CofiPRT** [comment]
**[Update]** This only happens **CLIENT SIDE**.

Upon spawning, the client world does some `Entity.readNbt()` stuff, where it calls `Entity.setGlowing()` with `false`.

Two things happen there - a glowing **boolean** gets set to `false`, but a glowing **flag** gets set to the value of `isGlowing()`, which is Mixin-ed in to return `true` due to step **2** in my post.

The vanilla behavior on the client (when the outlines are turned off) is to use that flag instead of the boolean - the flag requires an update when the mod's outlines are turned off.

**Comment by adamviola** [comment]
Thanks! Merged your PR.
