### ISSUE TITLE
Player Team Coloring works bad with some colors

### ISSUE THREAD

**Issue by Calvineries** [adamviola/EntityOutliner#13]
This feature works correctly with some colors, but not with others.
For example, players in yellow (&e) team, with their names in yellow in tab, have their outlines in pink.
Players in dark blue (&1) have theirs outlines in green.
Players in pink (&d) have theirs outlines in yellow

![image](https://user-images.githubusercontent.com/29179001/177047979-9848c256-29b7-4d75-8a1a-2814d7e75241.png)
![image](https://user-images.githubusercontent.com/29179001/177047771-1adff702-adac-4b86-b7eb-85660dfe0647.png)
![image](https://user-images.githubusercontent.com/29179001/177047775-01db8c75-8387-44fd-a391-a27553345386.png)
("Joueur" = "Player")

**Comment by adamviola** [comment]
Thanks for reporting this! Will be fixed soon.

**Comment by adamviola** [comment]
This issue is fixed! Uploaded the jar to Curseforge as v1.2.4.
