### ISSUE TITLE
[Feature Request] Update to 1.20

### ISSUE THREAD

**Issue by lightumcc** [adamviola/EntityOutliner#23]
https://github.com/adamviola/EntityOutliner/pull/22

**Comment by chenjunfu2** [comment]
+1

**Comment by n0rbyt3** [comment]
My latest pull request supports 1.20.4: #29

**Comment by n0rbyt3** [comment]
I'll release a new version for Minecraft 1.20.4, 1.19.4, 1.18.2, 1.17.1 and 1.16.5 soon which nearly rewrites the mod except for its basic algorithm.

The new version allows to toggle team colors so you can choose if you want to highlight players with their team color.

You can also get notified via chat if an entity is found that should be highlighted.

Finally, a feature request has been implemented to treat adults and babies different. This allows you to find baby pandas or mushroom cows in a crowd of adults.

**Comment by chenjunfu2** [comment]
I'm very much looking forward to this powerful update, thank you

**Comment by n0rbyt3** [comment]
Since this mod is discontinued, I'll not create new pull requests. To get a sneak peak on my progress, check out the attached files for Minecraft 1.19.4 and 1.20.4. Other versions are already supported, but I'll release them later under other conditions.

[entity-outliner-1.3.0+1.19.4.jar.zip](https://github.com/adamviola/EntityOutliner/files/13972888/entity-outliner-1.3.0%2B1.19.4.jar.zip)
[entity-outliner-1.3.0+1.20.4.jar.zip](https://github.com/adamviola/EntityOutliner/files/13972890/entity-outliner-1.3.0%2B1.20.4.jar.zip)

**Comment by Utopia1916** [comment]
> 我最新的拉取请求支持 1.20.4：#29

hero , love u

**Comment by n0rbyt3** [comment]
And here's a quick build for 1.20.5 / 1.20.6.

[entityoutliner-1.3.0+1.20.5.zip](https://github.com/adamviola/EntityOutliner/files/15106979/entityoutliner-1.3.0%2B1.20.5.zip)

**Comment by n0rbyt3** [comment]
1.21 anyone? :)

~[entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15858830/entityoutliner-1.3.0%2B1.21.jar.zip)~

edit: new version with team color bugfix:
[entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15928986/entityoutliner-1.3.0%2B1.21.jar.zip)

**Comment by lightumcc** [comment]
> 1.21 anyone? :)
> 
> [entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15858830/entityoutliner-1.3.0%2B1.21.jar.zip)

I suggest you fork this repo and release mods directly since the author seems like no longer actively maintenance

**Comment by n0rbyt3** [comment]
> I suggest you fork this repo and release mods directly since the author seems like no longer actively maintenance

I already have a fork and want to release it but under another conditions. That's why I re-use this repository for now. I also need another maintainer to create a more advanced UI. I have more ideas in mind. Maybe I'll start slow by releasing this mod with my extensions with a new name and icon. Don't know what seems to be the best way.

**Comment by lightumcc** [comment]
> > I suggest you fork this repo and release mods directly since the author seems like no longer actively maintenance
> 
> I already have a fork and want to release it but under another conditions. That's why I re-use this repository for now. I also need another maintainer to create a more advanced UI. I have more ideas in mind. Maybe I'll start slow by releasing this mod with my extensions with a new name and icon. Don't know what seems to be the best way.

I see. Thank you for your contribution.

**Comment by Calvineries** [comment]
> 1.21 anyone? :)
> 
> [entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15858830/entityoutliner-1.3.0%2B1.21.jar.zip)

Team colors don't seem to work properly in 1.21, for example: try a bedwars: the red team has the outline in dark blue.

**Comment by n0rbyt3** [comment]
> Team colors don't seem to work properly in 1.21, for example: try a bedwars: the red team has the outline in dark blue.

Team colors are sent from the server. Maybe the server assigns the same color to all teams as anti-cheat protection. Note: Player names are colored independent.

There is no logic inside the mod to guess the "correct" color.

**Comment by Calvineries** [comment]
> > Team colors don't seem to work properly in 1.21, for example: try a bedwars: the red team has the outline in dark blue.
> 
> Team colors are sent from the server. Maybe the server assigns the same color to all teams as anti-cheat protection. Note: Player names are colored independent.
> 
> There is no logic inside the mod to guess the "correct" color.

The mod detects colors, there was already this same problem some time ago and the author of the mod fixed it.
Issue : https://github.com/adamviola/EntityOutliner/issues/13
Commit : https://github.com/adamviola/EntityOutliner/commit/0a632120923e865d8c0f4ef13853016f9d9689e1

You can try going in singleplayer and do:
1) /team create NewTeam
2) /team join NewTeam
3) /team modify NewTeam color white
Your outline is white.
4) /team modify NewTeam color red
Your outline is dark blue instead of red.

**Comment by n0rbyt3** [comment]
> You can try going in singleplayer and do:
> 
> 1. /team create NewTeam
> 2. /team join NewTeam
> 3. /team modify NewTeam color white
>    Your outline is white.
> 4. /team modify NewTeam color red
>    Your outline is dark blue instead of red.

Thank you, I've fixed it. The protocol has changed. Colors are provided as ABGR value instead of ARGB now. See my edited comment above with a new upload.

**Comment by znopp** [comment]
Thank you @n0rbyt3 for updating!

**Comment by lsp7878578** [comment]
> 有人知道 1.21 吗？:)
> 
> ~[entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15858830/entityoutliner-1.3.0%2B1.21.jar.zip)~
> 
> 编辑：具有团队颜色错误修复的新版本： [entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15928986/entityoutliner-1.3.0%2B1.21.jar.zip)



> 1.21 anyone? :)
> 
> ~[entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15858830/entityoutliner-1.3.0%2B1.21.jar.zip)~
> 
> edit: new version with team color bugfix: [entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15928986/entityoutliner-1.3.0%2B1.21.jar.zip)



> 1.21 anyone? :)
> 
> ~[entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15858830/entityoutliner-1.3.0%2B1.21.jar.zip)~
> 
> edit: new version with team color bugfix: [entityoutliner-1.3.0+1.21.jar.zip](https://github.com/user-attachments/files/15928986/entityoutliner-1.3.0%2B1.21.jar.zip)

I still have team color display error with the new version, minecraft version 1.21, fabric version 0.15.11

**Comment by n0rbyt3** [comment]
> I still have team color display error with the new version, minecraft version 1.21, fabric version 0.15.11

Please use my initial 1.21 version. This will work (again). I need to investigate why.

**Comment by lsp7878578** [comment]
> > 我在新版本、minecraft 版本 1.21、Fabric 版本 0.15.11 中仍然存在团队颜色显示错误
> 
> 请使用我的初始 1.21 版本。这将（再次）起作用。我需要调查一下原因。

Request an update to 1.21.4, Hero.1.3.0 does not work with 1.21.3.
