### ISSUE TITLE
Add an option to make the outline the color of the team

### ISSUE THREAD

**Issue by vi945786** [adamviola/EntityOutliner#6]
Add an option to make the outline the color of the team

**Comment by adamviola** [comment]
I haven't forgotten this request!

Added this feature along with the update for 1.19! See the [v1.2.3 release](https://github.com/adamviola/EntityOutliner/releases/tag/v1.2.3) or [Curseforge file](https://www.curseforge.com/minecraft/mc-mods/entity-outliner/files/3834216) to download.

**Comment by vi945786** [comment]
i just used a few mixins but thanks
